# Generated by Django 6.0.3 on 2026-03-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updatedat',
            new_name='updated_at',
        ),
    ]
