# Generated by Django 6.0.3 on 2026-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=20)),
                ('about_description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'about',
            },
        ),
    ]
